### ISSUE TITLE
Зовсім не працює

### ISSUE THREAD

**Issue by CatDogFishFrog** [G0od1k/rezka-dl#1]
Радий що знайшов таку гарну ідею, але воно не працює зовсім.

У серіалах взагалі не вдається обрати серію чи серії для завантаження.
(перевіряв тут: https://rezka.ag/series/comedy/1814-ofis-2005.html#t:375-s:7-e:9)
![image](https://github.com/G0od1k/rezka-dl/assets/24408443/9580009e-f958-4376-9e78-e354a514d588)

Але, якщо клацнути "Вибрати все", то щось все ж таки з'являється, але кнопка "Завантажити" нічого не робить.
![image](https://github.com/G0od1k/rezka-dl/assets/24408443/7847fc9e-9f4f-474e-b958-292a6a6a2c2e)

Односерійний фільм, звісно, обирає, але кнопка "Завантажити" все ще не дає ніяких результатів.
(перевіряв тут: https://rezka.ag/films/drama/53678-kit-2022.html)
![image](https://github.com/G0od1k/rezka-dl/assets/24408443/9b266eed-f21c-4857-af17-158067885aa5)

Браузер Microsoft Edge.

**Comment by G0od1k** [comment]
Дякую за зворотний зв'язок, все виправив.

> У серіалах взагалі не вдається обрати серію чи серії для завантаження.

Що до цього. Розширення працю на тому що перехватує зґенеровані сайтом прямі посилання на відео файл.
Топто у спливаючому вікні відображаються лише ті серії для яких є посилання. Щоб посилання було зґенеровано сайтом, треба відкрити (запускати/програвати необов'язково) серії. Проще кажучи вам треба або власноруч відкривати кожну серію, або натискнути `Вибрати все` для автоматичного вибірання усіх серій.
